name: magic_calendar
description: "É um aplicativo fechado para ajudar"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.1.3
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^0.13.3
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/